spring:
  datasource:
    url: jdbc:mysql://localhost/persons_db?serverTimezone=UTC
    username: root
    password: 101mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    banner-mode: off
